{{- if not .Values.github.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-scanner.fullname" . }}-secrets
  namespace: {{ include "github-scanner.namespace" . }}
  labels:
    {{- include "github-scanner.labels" . | nindent 4 }}
type: Opaque
stringData:
  github-token: {{ .Values.github.token | quote }}
  {{- if not .Values.database.external.existingSecret }}
  database-url: {{ include "github-scanner.databaseUrl" . | quote }}
  {{- end }}
{{- end }}
